function [bb,bp] = draw_box(parent,boxTitle,channelName,changeChannelName,filenameContains,tabColor)
bp = uix.BoxPanel('Parent', parent, 'Title', boxTitle, 'Padding', 5, ...
     'TitleColor', tabColor, 'ForegroundColor', 'black', 'Tag', sprintf('channelField%d', numel(parent.Children)));
 
bb1(1) = uix.VButtonBox('Parent', bp, 'VerticalAlignment', 'top' ,...
    'HorizontalAlignment', 'left', 'ButtonSize', [400, 50]);

bb(2) = uix.HButtonBox('Parent', bb1(1), 'VerticalAlignment', 'top' ,...
    'HorizontalAlignment', 'left', 'ButtonSize', [200, 30], ...
    'VerticalAlignment', 'middle', 'Spacing', 5);

uicontrol('Parent', bb(2), 'Style', 'Text', 'String', 'Channel name', ...
    'HorizontalAlignment', 'left')

uicontrol('Parent', bb(2), 'Style', 'Edit', 'String', channelName, ...
    'HorizontalAlignment', 'left', 'Enable', changeChannelName, 'Tag', sprintf('channelName%d', numel(parent.Children)),...
    'Callback', @checkValidName)

bb(3) = uix.HButtonBox('Parent', bb1(1), 'VerticalAlignment', 'top' ,...
    'HorizontalAlignment', 'left', 'ButtonSize', [200, 30], ...
    'VerticalAlignment', 'middle', 'Spacing', 5);

uicontrol('Parent', bb(3), 'Style', 'Text', 'String', 'Filename contains', ...
    'HorizontalAlignment', 'left')

uicontrol('Parent', bb(3), 'Style', 'Edit', 'String', filenameContains, ...
    'HorizontalAlignment', 'left', 'Tag', sprintf('filenameContains%d', numel(parent.Children)))

uicontrol('Parent', bb(3), 'Style', 'Pushbutton', 'String', 'Update', ...
    'HorizontalAlignment', 'left', 'Callback', @updateFileList)
end

